// Code generated by MockGen. DO NOT EDIT.
// Source: internal\transport\graph\resolver.go

// Package mock_graph is a generated GoMock package.
package mock_graph

import (
	context "context"
	reflect "reflect"

	model "github.com/AntonovIv/post_graphQlservice/graph/model"
	gomock "github.com/golang/mock/gomock"
)

// MockpostsSrv is a mock of postsSrv interface.
type MockpostsSrv struct {
	ctrl     *gomock.Controller
	recorder *MockpostsSrvMockRecorder
}

// MockpostsSrvMockRecorder is the mock recorder for MockpostsSrv.
type MockpostsSrvMockRecorder struct {
	mock *MockpostsSrv
}

// NewMockpostsSrv creates a new mock instance.
func NewMockpostsSrv(ctrl *gomock.Controller) *MockpostsSrv {
	mock := &MockpostsSrv{ctrl: ctrl}
	mock.recorder = &MockpostsSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpostsSrv) EXPECT() *MockpostsSrvMockRecorder {
	return m.recorder
}

// CreateComment mocks base method.
func (m *MockpostsSrv) CreateComment(arg0 context.Context, arg1 model.CreateCommentReq) (*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", arg0, arg1)
	ret0, _ := ret[0].(*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockpostsSrvMockRecorder) CreateComment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockpostsSrv)(nil).CreateComment), arg0, arg1)
}

// CreateObserver mocks base method.
func (m *MockpostsSrv) CreateObserver(arg0 int) (int, chan *model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateObserver", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(chan *model.Comment)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateObserver indicates an expected call of CreateObserver.
func (mr *MockpostsSrvMockRecorder) CreateObserver(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateObserver", reflect.TypeOf((*MockpostsSrv)(nil).CreateObserver), arg0)
}

// CreatePost mocks base method.
func (m *MockpostsSrv) CreatePost(arg0 context.Context, arg1 model.CreatePostReq) (*model.PostListEl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", arg0, arg1)
	ret0, _ := ret[0].(*model.PostListEl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockpostsSrvMockRecorder) CreatePost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockpostsSrv)(nil).CreatePost), arg0, arg1)
}

// DeleteObserver mocks base method.
func (m *MockpostsSrv) DeleteObserver(arg0, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObserver", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObserver indicates an expected call of DeleteObserver.
func (mr *MockpostsSrvMockRecorder) DeleteObserver(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObserver", reflect.TypeOf((*MockpostsSrv)(nil).DeleteObserver), arg0, arg1)
}

// GetAllPosts mocks base method.
func (m *MockpostsSrv) GetAllPosts(arg0 context.Context) ([]*model.PostListEl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPosts", arg0)
	ret0, _ := ret[0].([]*model.PostListEl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPosts indicates an expected call of GetAllPosts.
func (mr *MockpostsSrvMockRecorder) GetAllPosts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPosts", reflect.TypeOf((*MockpostsSrv)(nil).GetAllPosts), arg0)
}

// GetCommentsForPost mocks base method.
func (m *MockpostsSrv) GetCommentsForPost(arg0 context.Context, arg1 *model.Post, arg2, arg3 int) ([]*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentsForPost", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentsForPost indicates an expected call of GetCommentsForPost.
func (mr *MockpostsSrvMockRecorder) GetCommentsForPost(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentsForPost", reflect.TypeOf((*MockpostsSrv)(nil).GetCommentsForPost), arg0, arg1, arg2, arg3)
}

// GetPostByID mocks base method.
func (m *MockpostsSrv) GetPostByID(arg0 context.Context, arg1 int) (*model.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostByID", arg0, arg1)
	ret0, _ := ret[0].(*model.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostByID indicates an expected call of GetPostByID.
func (mr *MockpostsSrvMockRecorder) GetPostByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostByID", reflect.TypeOf((*MockpostsSrv)(nil).GetPostByID), arg0, arg1)
}

// GetRepliesComments mocks base method.
func (m *MockpostsSrv) GetRepliesComments(arg0 context.Context, arg1 *model.Comment, arg2, arg3 int) ([]*model.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepliesComments", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*model.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepliesComments indicates an expected call of GetRepliesComments.
func (mr *MockpostsSrvMockRecorder) GetRepliesComments(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepliesComments", reflect.TypeOf((*MockpostsSrv)(nil).GetRepliesComments), arg0, arg1, arg2, arg3)
}

// NotifyObservers mocks base method.
func (m *MockpostsSrv) NotifyObservers(arg0 int, arg1 model.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyObservers", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyObservers indicates an expected call of NotifyObservers.
func (mr *MockpostsSrvMockRecorder) NotifyObservers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyObservers", reflect.TypeOf((*MockpostsSrv)(nil).NotifyObservers), arg0, arg1)
}
