package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/AntonovIv/post_graphQlservice/graph/model"
)

// GetAllPosts is the resolver for the GetAllPosts field.
func (r *queryResolver) GetAllPosts(ctx context.Context) ([]*model.PostListEl, error) {
	postAllResp, err := r.postService.GetAllPosts(ctx)
	return postAllResp, err

}
